package com.example.fleetech.retrofit.response

data class JTripData(
    val APIKey: String,
    val Address: String,
    val AddressType: String,
    val ContactMobile: String,
    val ContactPerson: String,
    val DLat: Double,
    val DLong: Double,
    val DeliveryDate: String,
    val DeliveryTime: String,
    val Destination: String,
    val DeviceID: String,
    val DispatchDate: String,
    val DispatchTime: String,
    val FleetLocation: String,
    val FleetStatus: String,
    val LRNO: String,
    val LoadingSlipFlag: String,
    val LockFlag: String,
    val MobileNo: String,
    val Msg: String,
    val OrderID: Int,
    val PODFlag: String,
    val Result: Int,
    val SLat: Double,
    val SLong: Double,
    val Source: String,
    val TripStatus: String,
    val TripSubStatus: String,
    val VDDistance: String,
    val VehicleCategory: String,
    val VehicleNo: String,
    val WalletBalColor: String,
    val WalletBalance: String,
    val ReportedFlag:String,
    val MultiRequestFlag:String
)